### ISSUE TITLE
Crash using industrial meat's meat packer.

### ISSUE THREAD

**Issue by Chenjox** [canitzp/Metalworks#1]
Placing a cable beside a meat packer crashes the server. Your methods are showing up in the log and crashlog.

Crashlog: https://pastebin.com/8N5EmHy3

**Comment by canitzp** [comment]
Thank you for the report. I'll take a look into this problem as soon as I'm home and keep you updated about it. Can you exactly descripe how your Energy cables are placed? E.g.: 'a battery and then some cable'

**Comment by Chenjox** [comment]
I placed a energy source (anything works, even rftools powercell) and a meat packer and connected them both. When placing the cable beside the meat packer it crashes. I dont even get to place it.

**Comment by canitzp** [comment]
Does it also happenes after the server restarts?

**Comment by canitzp** [comment]
Or is it a random error that only appearse some times?

**Comment by Chenjox** [comment]
After the server restarts, the cable doesn't "push" into the meat packer. after a block update it "pushes" energy in and the server crashes again

**Comment by canitzp** [comment]
Ok, I'll send you a test version soon. It would be reaaly nice if you can test if the crash happens again

**Comment by Chenjox** [comment]
Oki ^^ glad that i can help

**Comment by canitzp** [comment]
Here is a link to the new version. I changed only one thing, so it is very likely that it happens again: http://puu.sh/yWWUq/076edd6f50.jar

**Comment by Chenjox** [comment]
Amazingly, it works flawlessly
What did you do?

**Comment by canitzp** [comment]
Thats awesome. There is some log spam currently, but I release a official bug fix version at curseforge after fixeing the second posted bug and a non posted.

**Comment by Chenjox** [comment]
Awesome! Keep up the work you're doing!
