### ISSUE TITLE
Crash during loading

### ISSUE THREAD

**Issue by Neb2566** [canitzp/Metalworks#2]
Got crash during loading after updating to latest version

https://pastebin.com/jZxGNkLL

**Comment by canitzp** [comment]
Thanks for reporting this bug. I'll take a look into the issue when I'm home. This has to do with a compatibility issue with some other mod/mods. I keep you updated about the bug.

**Comment by Neb2566** [comment]
Wow that was a fast reply! Amazing mod and amazing people!

**Comment by canitzp** [comment]
I took a quick look into the code and it is a easy fix. I maybe release a bugfix version today (current time 5:18pm)

**Comment by canitzp** [comment]
@Neb2566 Can you test this test version with the exact same mod arragement and tell me the results? http://puu.sh/yWXNl/5b2786272b.jar

**Comment by Neb2566** [comment]
Yup that seems to be working, loaded the game just fine now. Thanks for super quick fix! :D

**Comment by canitzp** [comment]
OK thank. I release a new version now. It may take some time to appear on curseforge. I theory you can use the jar I gave you, I only changed the version number ;)
